## Basic Configuration
baseurl = "/"
languageCode = "en-US"
enableRobotsTXT = "true"
theme = "kiss"
title = "m-nakamura145"
copyright = "© 2020 Masato Nakamura"

## Site Settings
[params.info]
enableSocial = true # Adds OpenGraph and Twitter cards
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks

## Social Accounts
[params.social]
github = "m-nakamura145"
linkedin = "masato-nakamura-1081ab115"
twitter = "m_nakamura145"
email = "masato.nakamura145@gmail.com"

[params.social.config]
platforms = ["github","twitter","linkedin","email"]
